# Generated by Django 4.1.3 on 2022-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='years_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
