# Generated by Django 4.1.3 on 2022-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
